service: codepipeline-notifications
#app: your-app-name
#tenant: your-tenant-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"
frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  stage: test
  region: ap-southeast-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:*" # TODO: Need to limit the use of this to the Table.
    - Effect: Allow
      Action:
        - codepipeline:GetPipelineExecution
      Resource: "arn:aws:codepipeline:*:*:*" # TODO: Do we need to limit this?

  environment:
    DYNAMO_TABLE_NAME: slack-message-ids-${opt:stage, self:provider.stage}
    AWS_SLACK_NOTIFICATIONS_OAUTH_ACCESS_TOKEN: ${env:AWS_SLACK_NOTIFICATIONS_OAUTH_ACCESS_TOKEN}
    CODEPIPELINE_DEPLOYMENT_NOTIFICATIONS_SLACK_CHANNEL: ${env:CODEPIPELINE_DEPLOYMENT_NOTIFICATIONS_SLACK_CHANNEL}

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  codebuild-notifier:
    handler: bin/codebuild-notifier
    events:
      - cloudwatchEvent:
          name: "codebuild-slack-notifier"
          enabled: true
          event:
            source:
              - "aws.codebuild"
            detail-type:
              - "CodeBuild Build State Change"
              - "CodeBuild Build Phase Change"
  codepipeline-notifier:
    handler: bin/codepipeline-notifier
    events:
      - cloudwatchEvent:
          name: "codepipeline-slack-notifier"
          enabled: true
          event:
            source:
              - "aws.codepipeline"
            detail-type:
              - "CodePipeline Pipeline Execution State Change"
              - "CodePipeline Action Execution State Change"
              - "CodePipeline Stage Execution State Change"

resources:
  Resources:
    NewResource:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: buildID
            AttributeType: S
        KeySchema:
          - AttributeName: buildID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: 'slack-message-ids-${opt:stage, self:provider.stage}'